name: CI E2E

on:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Start scdf
        working-directory: ui
        run: |
          docker-compose -f cypress-dc-local.yml up -d
      - uses: cypress-io/github-action@v2
        with:
          working-directory: ui
          config-file: cypress-dc-local.json
          browser: chrome
          headless: true
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-artifacts
          path: |
            ui/cypress/screenshots/
            ui/cypress/videos/
